# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            HuS
tagline:          'Time is limited, To be a better man'
description:      'Hello,followDreamLgx! Here is my personal weblog about technology and life.'
url:              http://shelldone.com

author:
  name:           'followDreamLgx'
  url:            https://github.com/followDreamLgx

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : soohu
